$(document).ready(function () {
  // Animated title
  anime({
    targets: '#animatedTitle',
    translateY: [-50, 0],
    opacity: [0, 1],
    duration: 1500,
    easing: 'easeOutExpo'
  });

  // Initialize Leaflet map
  const map = L.map('map').setView([20, 0], 2);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '© OpenStreetMap contributors'
  }).addTo(map);

  let countryData = [];

  function displayCountry(country) {
    $('#passportCard').html(`<h3>${country.name}</h3><p>Capital: ${country.capital}</p><img src="${country.flag}" alt="Flag of ${country.name}" style="width: 100px; margin-top: 10px;">`);
    $('#populationCard').html(`<h3>Population</h3><p>${country.population}</p>`);
    $('#foodCard').html(`<h3>Famous Food</h3><p>${country.food}</p>`);
    $('#landmarkCard').html(`<h3>Landmark</h3><p>${country.landmark}</p>`);
    $('#funFactCard').html(`<h3>Fun Fact</h3><p>${country.fact}</p>`);
    $('#regionCard').html(`<h3>Region</h3><p>${country.region}</p>`);

    // Destroy any existing mini map before creating a new one
    if (window.miniMapInstance) window.miniMapInstance.remove();
    window.miniMapInstance = L.map('miniMap').setView(country.latlng, 5);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(window.miniMapInstance);
  }

  function setupEventHandlers() {
    $('#nextCountry').on('click', function () {
      const randomIndex = Math.floor(Math.random() * countryData.length);
      displayCountry(countryData[randomIndex]);
    });

    $('#searchInput').on('keypress', function (e) {
      if (e.which === 13) {
        const input = $(this).val().toLowerCase();
        const match = countryData.find(c => c.name.toLowerCase() === input);
        if (match) {
          $('#homePage').hide();
          $('#countryPage').show();
          displayCountry(match);
        }
      }
    });

    $('#backToMap').on('click', function () {
      $('#countryPage').hide();
      $('#homePage').show();
    });

    map.on('click', function () {
      const randomIndex = Math.floor(Math.random() * countryData.length);
      $('#homePage').hide();
      $('#countryPage').show();
      displayCountry(countryData[randomIndex]);
    });
  }

  // Fetch countries from REST Countries API
  async function loadCountries() {
    try {
      const response = await fetch('https://restcountries.com/v3.1/all?fields=name,capital,population,region,latlng,flags');
      const data = await response.json();
      const funFact = {
        "Afghanistan": "Afghanistan is home to one of the world's oldest oil paintings, found in the Bamiyan Caves.",
        "Algeria": "Algeria is the largest country in Africa by land area.",
        "Argentina": "Argentina is the birthplace of the tango dance.",
        "Australia": "Australia is home to more kangaroos than people.",
        "Bangladesh": "Bangladesh has the world's largest river delta: the Sundarbans, also home to Bengal tigers.",
        "Belgium": "Belgium is known for inventing fries (yes, 'French' fries!).",
        "Brazil": "Brazil is the only country in South America that speaks Portuguese.",
        "Canada": "Canada has more lakes than the rest of the world combined.",
        "Chile": "Chile is home to the world's driest desert, the Atacama.",
        "China": "China invented paper, printing, gunpowder, and the compass—called the Four Great Inventions.",
        "Colombia": "Colombia is one of the most biodiverse countries in the world.",
        "Czechia": "Czechia (Czech Republic) has the most castles per square mile in Europe.",
        "Denmark": "Denmark is consistently ranked one of the happiest countries in the world.",
        "Dominican Republic": "The Dominican Republic was the site of the first European settlement in the Americas.",
        "Egypt": "Ancient Egypt was among the first civilizations to use writing—hieroglyphics.",
        "Ethiopia": "Ethiopia is the only African country never to be colonized.",
        "Finland": "Finland has more saunas than cars!",
        "France": "France is the most visited country in the world.",
        "Germany": "Germany is home to over 1,500 varieties of sausages.",
        "Ghana": "Ghana was the first African country to gain independence from colonial rule in 1957.",
        "Greece": "Greece is considered the cradle of Western civilization and democracy.",
        "Hungary": "Hungary has a spa culture, with over 1,000 hot springs across the country.",
        "India": "India is the world's largest producer of films—Bollywood makes over 1,000 movies a year.",
        "Indonesia": "Indonesia has over 17,000 islands—only about 6,000 are inhabited.",
        "Iran": "Iran is home to one of the world's oldest civilizations, with cities dating back thousands of years.",
        "Iraq": "Iraq is the site of ancient Mesopotamia, known as the cradle of civilization.",
        "Ireland": "Ireland has no native snakes—thanks to legend, St. Patrick chased them away.",
        "Israel": "Israel has the most startups per capita in the world.",
        "Italy": "Italy has more UNESCO World Heritage Sites than any other country.",
        "Japan": "Japan has a 'crying sumo' contest where wrestlers try to make babies cry for good luck.",
        "Kenya": "Kenya is famous for its long-distance runners, many of whom come from the Rift Valley.",
        "Malaysia": "Malaysia has the world's largest cave chamber—Sarawak Chamber in Borneo.",
        "Mexico": "Mexico introduced chocolate, chilies, and corn to the world.",
        "Morocco": "Morocco is home to the world's oldest university—University of al-Qarawiyyin in Fez.",
        "Netherlands": "About a quarter of the Netherlands lies below sea level.",
        "New Zealand": "New Zealand has more sheep than people—about 5 to 1.",
        "Nigeria": "Nigeria is the most populous country in Africa and has a booming film industry called Nollywood.",
        "Norway": "Norway introduced the world to the paperclip!",
        "Pakistan": "Pakistan is home to the world's second-highest mountain—K2.",
        "Peru": "Peru is home to Machu Picchu, an ancient Incan city hidden in the Andes.",
        "Philippines": "The Philippines is made up of over 7,000 islands.",
        "Poland": "Poland is home to the world's biggest castle—Malbork Castle.",
        "Portugal": "Portugal is the oldest country in Europe with the same defined borders since 1139.",
        "Russia": "Russia is the largest country in the world by land area.",
        "Saudi Arabia": "Saudi Arabia has no rivers—none at all!",
        "South Africa": "South Africa has three capital cities: Pretoria, Cape Town, and Bloemfontein.",
        "South Korea": "South Korea is a global leader in internet speed and tech innovation.",
        "Spain": "Spain produces over 40% of the world's olive oil.",
        "Sweden": "Sweden gives each citizen access to a public 'right to roam' in nature—called 'Allemansrätten'.",
        "Thailand": "Thailand is home to the world's smallest mammal: the bumblebee bat.",
        "United States": "The U.S. has no official language at the federal level—even though English is the most spoken.",
        "Albania": "Albania has over 750,000 bunkers, built during the communist era.",
        "Andorra": "Andorra is the only co-principality in the world, ruled by two princes (the President of France and the Bishop of Urgell).",
        "Angola": "Angola's Kalandula Falls are one of Africa's largest waterfalls by volume.",
        "Antigua and Barbuda": "Antigua and Barbuda has a beach for every day of the year—365 in total!",
        "Armenia": "Armenia was the first country to adopt Christianity as its state religion in 301 AD.",
        "Austria": "Austria is the birthplace of Mozart, Freud, and the waltz.",
        "Azerbaijan": "Azerbaijan is called the 'Land of Fire' due to its natural gas flares.",
        "Bahamas": "The Bahamas has the clearest water in the world, with visibility up to 200 feet.",
        "Bahrain": "Bahrain is home to the ancient Dilmun civilization, one of the oldest trading hubs.",
        "Barbados": "Barbados is the birthplace of rum, with the oldest rum distillery (Mount Gay, 1703).",
        "Belarus": "Belarus is home to Europe's largest mammal—the European bison.",
        "Belize": "Belize's Great Blue Hole is a giant marine sinkhole popular with divers.",
        "Benin": "Benin is the birthplace of Vodun (Voodoo), now a national religion.",
        "Bhutan": "Bhutan measures its success by Gross National Happiness, not GDP.",
        "Bolivia": "Bolivia's Salar de Uyuni is the world's largest salt flat, reflecting the sky like a mirror.",
        "Botswana": "Botswana's Okavango Delta is the world's largest inland delta.",
        "Brunei": "Brunei's Sultan Hassanal Bolkiah once had the world's largest residential palace.",
        "Bulgaria": "Bulgaria invented the Cyrillic alphabet, used in many Slavic languages.",
        "Burkina Faso": "Burkina Faso's name means 'Land of Honest Men' in local languages.",
        "Burundi": "Burundi is home to the world's longest freshwater lake, Lake Tanganyika.",
        "Cambodia": "Cambodia's Angkor Wat is the largest religious monument in the world.",
        "Cameroon": "Cameroon is called 'Africa in Miniature' for its diverse landscapes and cultures.",
        "Cape Verde": "Cape Verde's music, morna, is UNESCO-listed (like Cesária Évora's songs).",
        "Central African Republic": "The Central African Republic has the world's second-largest rainforest after the Amazon.",
        "Chad": "Chad's Ennedi Plateau has ancient rock formations and cave paintings.",
        "Comoros": "Comoros is the world's largest producer of ylang-ylang (used in perfumes).",
        "Congo (Brazzaville)": "Congo-Brazzaville is home to the 'Pointe-Noire' oil fields, vital to its economy.",
        "Congo (Kinshasa)": "The Congo River is the world's deepest (720 ft) and second-largest by volume.",
        "Costa Rica": "Costa Rica generates over 99% of its electricity from renewable sources.",
        "Croatia": "Croatia's Dalmatian Coast inspired the spotted Dalmatian dog breed's name.",
        "Cuba": "Cuba has one of the world's highest doctor-to-patient ratios.",
        "Cyprus": "Cyprus is the mythical birthplace of Aphrodite, the Greek goddess of love.",
        "Djibouti": "Djibouti's Lake Assal is Africa's lowest point and one of the saltiest lakes.",
        "Ecuador": "Ecuador's Galápagos Islands inspired Darwin's theory of evolution.",
        "El Salvador": "El Salvador is the smallest and most densely populated Central American country.",
        "Equatorial Guinea": "Equatorial Guinea is the only African country with Spanish as an official language.",
        "Eritrea": "Eritrea's capital, Asmara, is a UNESCO site for its Italian modernist architecture.",
        "Estonia": "Estonia has the world's highest number of meteorite craters per square mile.",
        "Eswatini": "Eswatini (Swaziland) is Africa's last absolute monarchy.",
        "Fiji": "Fiji's International Date Line runs through Taveuni, making it 'where tomorrow begins.'",
        "Gabon": "Gabon has 11% of its land as national parks, home to forest elephants.",
        "Gambia": "The Gambia is the smallest country on mainland Africa, surrounded by Senegal.",
        "Georgia": "Georgia is home to the world's deepest cave, Veryovkina Cave (7,257 ft).",
        "Guatemala": "Guatemala's Tikal was one of the most powerful Mayan cities.",
        "Guinea": "Guinea holds over half the world's bauxite reserves (used for aluminum).",
        "Guinea-Bissau": "Guinea-Bissau's Bijagós Islands are a UNESCO Biosphere Reserve.",
        "Guyana": "Guyana is the only South American country where English is the official language.",
        "Haiti": "Haiti was the first independent nation in Latin America (1804) and first post-colonial Black-led republic.",
        "Honduras": "Honduras' Río Plátano Biosphere Reserve is a UNESCO site with jaguars and macaws.",
        "Iceland": "Iceland has no mosquitoes—they can't survive the climate!",
        "Jamaica": "Jamaica is the birthplace of reggae music and Bob Marley.",
        "Jordan": "Jordan's Petra is a 2,000-year-old city carved into rose-red cliffs.",
        "Kazakhstan": "Kazakhstan is the world's largest landlocked country and home to the Baikonur Cosmodrome.",
        "Kiribati": "Kiribati is the only country in all four hemispheres (crossing the equator and IDL).",
        "Kuwait": "Kuwait's oil reserves are the sixth-largest in the world.",
        "Kyrgyzstan": "Kyrgyzstan's Issyk-Kul is the world's second-largest alpine lake (never freezes).",
        "Laos": "Laos is the most bombed country per capita due to the Vietnam War's 'Secret War'.",
        "Latvia": "Latvia invented the Christmas tree tradition (first decorated in Riga in 1510).",
        "Lebanon": "Lebanon's Byblos is one of the oldest continuously inhabited cities (since 5000 BCE).",
        "Lesotho": "Lesotho is the only country entirely above 1,000 meters in elevation.",
        "Liberia": "Liberia was founded by freed American slaves and Africa's first republic (1847).",
        "Libya": "Libya's Sahara has the world's highest recorded temperature (136°F/58°C in 1922).",
        "Liechtenstein": "Liechtenstein is the world's largest producer of false teeth.",
        "Lithuania": "Lithuania was the last pagan country in Europe, converting to Christianity in 1387.",
        "Luxembourg": "Luxembourg has the world's highest GDP per capita.",
        "Madagascar": "Madagascar is home to lemurs, found nowhere else on Earth.",
        "Malawi": "Malawi's Lake Malawi has more fish species than any other lake.",
        "Maldives": "The Maldives is the world's lowest country, averaging 1.5m above sea level.",
        "Mali": "Mali's Timbuktu was a medieval center of learning with thousands of ancient manuscripts.",
        "Malta": "Malta's Megalithic Temples are older than Stonehenge and the Pyramids.",
        "Marshall Islands": "The Marshall Islands' Bikini Atoll gave its name to the bikini swimsuit after nuclear tests.",
        "Mauritania": "Mauritania's ancient Chinguetti libraries hold 1,000-year-old Quranic texts.",
        "Mauritius": "Mauritius is the only known home of the extinct dodo bird.",
        "Micronesia": "Micronesia's Nan Madol is a ruined city built on coral reefs.",
        "Moldova": "Moldova's Mileștii Mici wine cellar holds the world's largest wine collection (2 million bottles).",
        "Monaco": "Monaco is the world's most densely populated country.",
        "Mongolia": "Mongolia is the least densely populated country on Earth.",
        "Montenegro": "Montenegro's Bay of Kotor is Europe's southernmost fjord.",
        "Mozambique": "Mozambique's Island of Mozambique is a UNESCO site with Portuguese colonial history.",
        "Myanmar": "Myanmar's Shwedagon Pagoda is covered in 27 tons of gold leaf.",
        "Namibia": "Namibia's Namib Desert is the world's oldest desert (55 million years).",
        "Nauru": "Nauru is the world's smallest island nation and has no capital city.",
        "Nepal": "Nepal's Mount Everest is the tallest peak on Earth (29,032 ft).",
        "Nicaragua": "Nicaragua's Lake Nicaragua has freshwater sharks.",
        "Niger": "Niger's Agadez Mosque is the tallest mud-brick structure in the world.",
        "North Korea": "North Korea's Pyongyang Metro is the deepest subway system (360 ft underground).",
        "North Macedonia": "North Macedonia's Lake Ohrid is one of Europe's oldest lakes (4 million years).",
        "Oman": "Oman's Sultan Qaboos Grand Mosque has the world's second-largest handwoven carpet.",
        "Palau": "Palau's Jellyfish Lake lets you swim with harmless golden jellyfish.",
        "Panama": "Panama's Darién Gap is the only break in the Pan-American Highway.",
        "Papua New Guinea": "Papua New Guinea has over 800 languages, the most linguistically diverse country.",
        "Paraguay": "Paraguay's Itaipu Dam is the world's second-largest hydroelectric dam.",
        "Qatar": "Qatar is the richest country in the world by GDP per capita.",
        "Romania": "Romania's Carpathian Mountains host Europe's largest brown bear population.",
        "Rwanda": "Rwanda is the world's leader in gender equality, with women holding 61% of parliamentary seats.",
        "Samoa": "Samoa switched the International Date Line in 2011, becoming 'the place where time begins.'",
        "San Marino": "San Marino is the world's oldest republic (founded in 301 AD).",
        "Sao Tome and Principe": "São Tomé and Príncipe is Africa's smallest country by population.",
        "Senegal": "Senegal's Pink Lake (Lac Rose) has water as salty as the Dead Sea.",
        "Serbia": "Serbia's Đavolja Varoš ('Devil's Town') has eerie rock formations.",
        "Seychelles": "Seychelles' Vallée de Mai is home to the rare coco de mer palm.",
        "Sierra Leone": "Sierra Leone's name means 'Lion Mountains,' though lions no longer live there.",
        "Singapore": "Singapore is the only island city-state in the world.",
        "Slovakia": "Slovakia has the world's highest number of castles and chateaux per capita.",
        "Slovenia": "Slovenia's Postojna Cave has an underground train and 'dragon' salamanders.",
        "Solomon Islands": "The Solomon Islands' Kennedy Island is where JFK's PT-109 crew swam to safety in WWII.",
        "Somalia": "Somalia has the longest coastline in mainland Africa.",
        "Sri Lanka": "Sri Lanka's Sigiriya is an ancient 'Lion Rock' fortress with frescoes.",
        "Sudan": "Sudan has more pyramids than Egypt (over 200 ancient Nubian pyramids).",
        "Suriname": "Suriname is the smallest country in South America and the only Dutch-speaking one.",
        "Switzerland": "Switzerland's Gotthard Base Tunnel is the world's longest railway tunnel (35.5 miles).",
        "Syria": "Syria's Aleppo is one of the oldest continuously inhabited cities (since 6,000 BCE).",
        "Taiwan": "Taiwan's Taipei 101 was the world's tallest building from 2004 to 2010.",
        "Tajikistan": "Tajikistan's Pamir Highway is one of the world's highest-altitude roads.",
        "Tanzania": "Tanzania's Mount Kilimanjaro is Africa's highest peak and a dormant volcano.",
        "Timor-Leste": "Timor-Leste (East Timor) is Asia's youngest country, independent since 2002.",
        "Togo": "Togo's name comes from 'Togodo,' meaning 'behind the river' in Ewe.",
        "Tonga": "Tonga is the only Pacific monarchy and never colonized.",
        "Trinidad and Tobago": "Trinidad and Tobago invented the steelpan, the only acoustic instrument made in the 20th century.",
        "Tunisia": "Tunisia's El Jem Amphitheater is the largest Roman colosseum in Africa.",
        "Turkey": "Turkey's Istanbul is the only city spanning two continents (Europe and Asia).",
        "Turkmenistan": "Turkmenistan's Darvaza Gas Crater, the 'Door to Hell,' has burned for 50+ years.",
        "Tuvalu": "Tuvalu earns royalties from its '.tv' internet domain, used by streaming platforms.",
        "Uganda": "Uganda is home to half the world's remaining mountain gorillas.",
        "Ukraine": "Ukraine's 'Tunnel of Love' is a magical tree-covered railway track in Klevan.",
        "United Arab Emirates": "The UAE's Burj Khalifa is the world's tallest building (2,717 ft).",
        "United Kingdom": "The UK's London Underground is the oldest metro system (opened in 1863).",
        "Uruguay": "Uruguay was the first country to provide a laptop for every primary school student.",
        "Uzbekistan": "Uzbekistan's Samarkand was a key Silk Road city and is over 2,700 years old.",
        "Vanuatu": "Vanuatu's Mount Yasur is one of the world's most accessible active volcanoes.",
        "Vatican City": "Vatican City is the world's smallest country by size and population.",
        "Venezuela": "Venezuela's Angel Falls is the world's highest uninterrupted waterfall (3,212 ft).",
        "Vietnam": "Vietnam's Sơn Đoòng Cave is the world's largest cave by volume.",
        "Yemen": "Yemen's Socotra Island has alien-like dragon's blood trees.",
        "Zambia": "Zambia's Victoria Falls is the world's largest waterfall by combined width and height.",
        "Zimbabwe": "Zimbabwe's Great Zimbabwe Ruins are the largest ancient stone structures in Africa south of the pyramids."
      };

      const foodMap = {
        "Afghanistan": "Kabuli Pulao",
        "Albania": "Tavë Kosi",
        "Algeria": "Couscous",
        "Andorra": "Escudella",
        "Angola": "Moamba de Galinha",
        "Antigua and Barbuda": "Fungee and Pepperpot",
        "Argentina": "Asado",
        "Armenia": "Khorovats",
        "Australia": "Meat Pie",
        "Austria": "Wiener Schnitzel",
        "Azerbaijan": "Plov",
        "Bahamas": "Conch Salad",
        "Bahrain": "Machboos",
        "Bangladesh": "Hilsa Fish Curry",
        "Barbados": "Cou-Cou & Flying Fish",
        "Belarus": "Draniki",
        "Belgium": "Waffles",
        "Belize": "Rice and Beans with Stew Chicken",
        "Benin": "Pâte",
        "Bhutan": "Ema Datshi",
        "Bolivia": "Salteñas",
        "Bosnia and Herzegovina": "Ćevapi",
        "Botswana": "Seswaa",
        "Brazil": "Feijoada",
        "Brunei": "Ambuyat",
        "Bulgaria": "Banitsa",
        "Burkina Faso": "Riz Gras",
        "Burundi": "Ugali & Beans",
        "Cabo Verde": "Cachupa",
        "Cambodia": "Amok Trey",
        "Cameroon": "Ndolé",
        "Canada": "Poutine",
        "Central African Republic": "Cassava Leaf Stew",
        "Chad": "Boule",
        "Chile": "Empanadas",
        "China": "Dumplings",
        "Colombia": "Arepas",
        "Comoros": "Langouste a la Vanille",
        "Congo (Democratic Republic)": "Moambe Chicken",
        "Congo (Republic)": "Poulet Moambé",
        "Costa Rica": "Gallo Pinto",
        "Côte d'Ivoire": "Attiéké",
        "Croatia": "Peka",
        "Cuba": "Ropa Vieja",
        "Cyprus": "Halloumi & Souvla",
        "Czechia": "Svíčková",
        "Denmark": "Smørrebrød",
        "Djibouti": "Skoudehkaris",
        "Dominica": "Callaloo Soup",
        "Dominican Republic": "Mangu",
        "Ecuador": "Hornado",
        "Egypt": "Koshari",
        "El Salvador": "Pupusas",
        "Equatorial Guinea": "Succotash",
        "Eritrea": "Zigni",
        "Estonia": "Verivorst",
        "Eswatini": "Sishwala",
        "Ethiopia": "Injera",
        "Fiji": "Kokoda",
        "Finland": "Karjalanpiirakka",
        "France": "Croissant",
        "Gabon": "Poulet Nyembwe",
        "Gambia": "Domoda",
        "Georgia": "Khachapuri",
        "Germany": "Bratwurst",
        "Ghana": "Jollof Rice",
        "Greece": "Moussaka",
        "Grenada": "Oil Down",
        "Guatemala": "Kak'ik",
        "Guinea": "Poulet Yassa",
        "Guinea-Bissau": "Jollof Rice",
        "Guyana": "Pepperpot",
        "Haiti": "Griot",
        "Honduras": "Baleadas",
        "Hungary": "Goulash",
        "Iceland": "Hákarl",
        "India": "Biryani",
        "Indonesia": "Nasi Goreng",
        "Iran": "Fesenjan",
        "Iraq": "Masgouf",
        "Ireland": "Irish Stew",
        "Israel": "Shakshuka",
        "Italy": "Pizza",
        "Jamaica": "Ackee and Saltfish",
        "Japan": "Sushi",
        "Jordan": "Mansaf",
        "Kazakhstan": "Beshbarmak",
        "Kenya": "Nyama Choma",
        "Kiribati": "Palusami",
        "Korea (North)": "Naengmyeon",
        "Korea (South)": "Kimchi",
        "Kuwait": "Machboos",
        "Kyrgyzstan": "Beshbarmak",
        "Laos": "Larb",
        "Latvia": "Grey Peas with Bacon",
        "Lebanon": "Kibbeh",
        "Lesotho": "Papa",
        "Liberia": "Fufu & Soup",
        "Libya": "Bazin",
        "Liechtenstein": "Käsknöpfle",
        "Lithuania": "Cepelinai",
        "Luxembourg": "Judd mat Gaardebounen",
        "Madagascar": "Romazava",
        "Malawi": "Nsima",
        "Malaysia": "Nasi Lemak",
        "Maldives": "Mas Huni",
        "Mali": "Tiguadege Na",
        "Malta": "Stuffat tal-Fenek",
        "Marshall Islands": "Iakwe",
        "Mauritania": "Thieboudienne",
        "Mauritius": "Dholl Puri",
        "Mexico": "Tacos",
        "Micronesia": "Karahk",
        "Moldova": "Mămăligă",
        "Monaco": "Barbagiuan",
        "Mongolia": "Buuz",
        "Montenegro": "Njeguški Steak",
        "Morocco": "Tagine",
        "Mozambique": "Piri Piri Chicken",
        "Myanmar": "Mohinga",
        "Namibia": "Kapana",
        "Nauru": "Coconut Fish",
        "Nepal": "Momo",
        "Netherlands": "Stroopwafel",
        "New Zealand": "Pavlova",
        "Nicaragua": "Gallo Pinto",
        "Niger": "Dambou",
        "Nigeria": "Egusi Soup",
        "North Macedonia": "Tavče Gravče",
        "Norway": "Rakfisk",
        "Oman": "Shuwa",
        "Pakistan": "Biryani",
        "Palau": "Bat Soup",
        "Palestine": "Musakhan",
        "Panama": "Sancocho",
        "Papua New Guinea": "Mumu",
        "Paraguay": "Sopa Paraguaya",
        "Peru": "Ceviche",
        "Philippines": "Adobo",
        "Poland": "Pierogi",
        "Portugal": "Bacalhau",
        "Qatar": "Machboos",
        "Romania": "Sarmale",
        "Russia": "Borscht",
        "Rwanda": "Brochettes",
        "Saint Kitts and Nevis": "Goat Water",
        "Saint Lucia": "Green Fig & Saltfish",
        "Saint Vincent and the Grenadines": "Roasted Breadfruit & Jackfish",
        "Samoa": "Palusami",
        "San Marino": "Torta Tre Monti",
        "Sao Tome and Principe": "Calulu",
        "Saudi Arabia": "Kabsa",
        "Senegal": "Thieboudienne",
        "Serbia": "Ćevapi",
        "Seychelles": "Fish Curry",
        "Sierra Leone": "Cassava Leaves",
        "Singapore": "Hainanese Chicken Rice",
        "Slovakia": "Bryndzové Halušky",
        "Slovenia": "Potica",
        "Solomon Islands": "Poi",
        "Somalia": "Canjeero",
        "South Africa": "Bobotie",
        "South Sudan": "Kisra",
        "Spain": "Paella",
        "Sri Lanka": "Kottu Roti",
        "Sudan": "Ful Medames",
        "Suriname": "Pom",
        "Sweden": "Meatballs",
        "Switzerland": "Fondue",
        "Syria": "Kibbeh",
        "Taiwan": "Beef Noodle Soup",
        "Tajikistan": "Plov",
        "Tanzania": "Ugali",
        "Thailand": "Pad Thai",
        "Timor-Leste": "Ikan Pepes",
        "Togo": "Akoumé",
        "Tonga": "Lu Pulu",
        "Trinidad and Tobago": "Doubles",
        "Tunisia": "Couscous with Lamb",
        "Turkey": "Kebabs",
        "Turkmenistan": "Manti",
        "Tuvalu": "Pulaka",
        "Uganda": "Matoke",
        "Ukraine": "Varenyky",
        "United Arab Emirates": "Harees",
        "United Kingdom": "Fish and Chips",
        "United States": "Burgers",
        "Uruguay": "Chivito",
        "Uzbekistan": "Plov",
        "Vanuatu": "Lap Lap",
        "Vatican City": "Pasta (Italian-inspired)",
        "Venezuela": "Arepas",
        "Vietnam": "Pho",
        "Yemen": "Saltah",
        "Zambia": "Nshima",
        "Zimbabwe": "Sadza"
      };

      const landmarkMap = {
        "Afghanistan": "Blue Mosque of Mazar-i-Sharif",
        "Algeria": "Casbah of Algiers",
        "Argentina": "Iguazu Falls",
        "Australia": "Sydney Opera House",
        "Bangladesh": "Sundarbans Mangrove Forest",
        "Belgium": "Atomium",
        "Brazil": "Christ the Redeemer",
        "Canada": "CN Tower",
        "Chile": "Easter Island Moai",
        "China": "Great Wall",
        "Colombia": "Salt Cathedral of Zipaquira",
        "Czechia": "Prague Castle",
        "Denmark": "The Little Mermaid",
        "Dominican Republic": "Alcázar de Colón",
        "Egypt": "Pyramids of Giza",
        "Ethiopia": "Lalibela Churches",
        "Finland": "Helsinki Cathedral",
        "France": "Eiffel Tower",
        "Germany": "Brandenburg Gate",
        "Ghana": "Cape Coast Castle",
        "Greece": "Parthenon",
        "Hungary": "Buda Castle",
        "India": "Taj Mahal",
        "Indonesia": "Borobudur",
        "Iran": "Persepolis",
        "Iraq": "Ziggurat of Ur",
        "Ireland": "Cliffs of Moher",
        "Israel": "Western Wall",
        "Italy": "Colosseum",
        "Japan": "Mount Fuji",
        "Kenya": "Maasai Mara",
        "Malaysia": "Petronas Towers",
        "Mexico": "Chichen Itza",
        "Morocco": "Hassan II Mosque",
        "Netherlands": "Kinderdijk Windmills",
        "New Zealand": "Milford Sound",
        "Nigeria": "Zuma Rock",
        "Norway": "Geirangerfjord",
        "Pakistan": "Badshahi Mosque",
        "Peru": "Machu Picchu",
        "Philippines": "Chocolate Hills",
        "Poland": "Wawel Castle",
        "Portugal": "Belem Tower",
        "Russia": "Saint Basil's Cathedral",
        "Saudi Arabia": "Masjid al-Haram",
        "South Africa": "Table Mountain",
        "South Korea": "Gyeongbokgung Palace",
        "Spain": "La Sagrada Familia",
        "Sweden": "Vasa Museum",
        "Thailand": "Grand Palace",
        "United States": "Statue of Liberty"
      };

      // map to custom structure
      countryData = data.map(c => {
        const name = c.name.common; // define name first
        return {
          name,
          capital: c.capital ? c.capital[0] : 'N/A',
          population: (c.population / 1_000_000).toFixed(1) + 'M',
          food: foodMap[name] || 'Unknown Cuisine',
          landmark: landmarkMap[name] || 'Famous Landmark',
          region: `${c.region}`,
          fact: funFact[name] || '',
          latlng: c.latlng || [0, 0],
          flag: c.flags?.png || ''
        };
      });
      
      setupEventHandlers(); // set up buttons/ search after data loads
    } catch (err) {
      console.error('Error fetching country data:', err);
    }
  }

  loadCountries(); // start loading countries on page load
});
